baseURL = "https://tfong1.github.io"
languageCode = "en-us"
title = "Tony Fong's Portfolio Site"
theme = "lightbi-hugo"

[params]
    description = "Tony's Portfolio Site"
    previewCardImagePlacement = "top"
    [params.Author]
        name = "Tony Fong"
        website = "https://tfong1.github.io"
        authorPostImage = "https://github.com/TFong1.png"
        linkedin = "tonynfong"
        github = "TFong1"

